matrix:
  # This causes the build to complete immediately upon first failure or once
  # required jobs are green.
  fast_finish: true

  include:
    # Runs unit tests without emulators.
    - env: JOB=PR
      os: linux
      language: generic
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta
        - gem install coveralls-lcov
      script:
        - ./flutter/bin/flutter test --coverage

cache:
  directories:
    - $HOME/.pub-cache